name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi, wasm32-unknown-unknown

      - name: Install cargo leptos
        run: cargo install --locked cargo-leptos
      
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      
      - name: Build and test
        run: spin build && cargo test --verbose

  spin:
    needs: test
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi, wasm32-unknown-unknown

      - name: Install cargo leptos
        run: cargo install --locked cargo-leptos
        
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1

      - name: Build and deploy
        uses: fermyon/actions/spin/deploy@v1
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}